In [1]:
print('hello')

hello

In [ ]:
import pandas as pd
import numpy as np

def remuestrear(df, col_nombre, t_muestreo):
    columna_objetivo = col_nombre

    # 2. Creamos una máscara para filtrar las celdas:
    #    - Que el índice no sea múltiplo de t_muestreo
    #    - Que el valor no sea 0
    mascara = (df.index % t_muestreo != 0) & (df[columna_objetivo] != 0)

    # 3. Obtenemos los índices originales que cumplen la condición
    indices_originales = df.index[mascara]

    # 4. Calculamos el múltiplo de t_muestreo más cercano para cada índice original.
    #    Dividimos entre t_muestreo, redondeamos al entero más cercano y multiplicamos por t_muestreo.
    indices_nuevos = (np.round(indices_originales / t_muestreo) * t_muestreo).astype(int)

    # 5. Desplazamos los valores
    for idx_orig, idx_nuevo in zip(indices_originales, indices_nuevos):
        
        # Nos aseguramos de que el nuevo índice exista en el DataFrame
        # (por si el redondeo se pasa del límite del DataFrame)
        if idx_nuevo not in df.index:
            df.loc[idx_nuevo] = 0 # O crea la fila si lo prefieres
            
        # Sumamos el valor a la celda destino (por si hay varios valores que van a la misma celda)
        df.at[idx_nuevo, columna_objetivo] += df.at[idx_orig, columna_objetivo]
        
        # Ponemos la celda original a 0 (ya que hemos desplazado el valor)
        df.at[idx_orig, columna_objetivo] = 0

    return df

In [ ]:
datos = {
    'valores': [0, 10, 0, 0, 20, 0, 0, 30, 0, 0, 0, 40, 0]
}
df = pd.DataFrame(datos)

print("DataFrame Original:")
print(df)

salida = remuestrear(df, 'valores', 5)
print("\nDataFrame con los valores desplazados:")
print(salida)

DataFrame Original:
    valores
0         0
1        10
2         0
3         0
4        20
5         0
6         0
7        30
8         0
9         0
10        0
11       40
12        0

DataFrame con los valores desplazados:
    valores
0        10
1         0
2         0
3         0
4         0
5        50
6         0
7         0
8         0
9         0
10       40
11        0
12        0

In [2]:
import pickle
datos = dict()
for i in range(1,10):
    nombre_archivo = f"../Simulaciones/sim_{i}_data.pkl"

    with open(nombre_archivo, 'rb') as f:
        datos_recuperados = pickle.load(f)
    datos[i]=datos_recuperados
    print(type(datos_recuperados),len(datos_recuperados))

<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20

In [3]:
def estadisticas_rango(df, nombre_col = 'gluc_mg'):
    est =pd.DataFrame()
    columna = nombre_col

    # 2. Definimos los límites de los rangos (bins)
    # Esto creará los rangos: (0-18], (18-35], (35-60], (60-100]
    limites = [0, 69, 180, 700]

    # 3. (Opcional) Definimos etiquetas para que el resultado sea más fácil de leer
    nombres_rangos = ['TBR', 'TIR','TAR']

    # 4. Clasificamos los valores de la columna en los rangos usando pd.cut()
    est['Tiempo_en_rango'] = pd.cut(df[columna], bins=limites, labels=nombres_rangos)

    # 5. Calculamos el porcentaje
    # normalize=True devuelve proporciones (de 0 a 1). Multiplicamos por 100 para porcentaje.
    porcentajes = est['Tiempo_en_rango'].value_counts(normalize=True) * 100

    porcentajes_ok = {'TIR':[round(porcentajes['TIR'],2)],
                      'TAR':[round(porcentajes['TAR'],2)],
                      'TBR':[round(porcentajes['TBR'],2)]}
    return porcentajes_ok

estadisticas_rango(datos[1]['p_2'])

{'TIR': [27.99], 'TAR': [72.01], 'TBR': [0.0]}

In [5]:
est = pd.DataFrame(columns=['Simulacion','Paciente', 'TBR', 'TIR', 'TAR'])
# display(est)
for simu in range(1,10):
    for p in range(20):
        est_l = estadisticas_rango(datos[simu][f'p_{p}'])
        est_l.update({'Simulacion': [simu], 'Paciente': [p]})
        df_l = pd.DataFrame(est_l)
        est = pd.concat([est, df_l])
# est.head(20)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_28096\4009653070.py:8: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  est = pd.concat([est, df_l])

In [7]:
for i in range(1,10):
    display(est[est['Simulacion']==i])

  Simulacion Paciente  TBR     TIR    TAR
0          1        0  0.0   81.41  18.59
0          1        1  0.0   98.31   1.69
0          1        2  0.0   27.99  72.01
0          1        3  0.0   24.59  75.41
0          1        4  0.0    1.64  98.36
0          1        5  0.0  100.00   0.00
0          1        6  0.0   91.11   8.89
0          1        7  0.0   99.83   0.17
0          1        8  0.0    3.43  96.57
0          1        9  0.0    1.92  98.08
0          1       10  0.0   23.01  76.99
0          1       11  0.0   38.75  61.25
0          1       12  0.0   40.13  59.87
0          1       13  0.0  100.00   0.00
0          1       14  0.0   83.96  16.04
0          1       15  0.0    1.75  98.25
0          1       16  0.0   10.03  89.97
0          1       17  0.0   73.28  26.72
0          1       18  0.0   91.28   8.72
0          1       19  0.0   20.95  79.05

  Simulacion Paciente  TBR     TIR    TAR
0          2        0  0.0   80.74  19.26
0          2        1  0.0   98.09   1.91
0          2        2  0.0   28.67  71.33
0          2        3  0.0   20.40  79.60
0          2        4  0.0    1.99  98.01
0          2        5  0.0  100.00   0.00
0          2        6  0.0   91.54   8.46
0          2        7  0.0   98.67   1.33
0          2        8  0.0    3.82  96.18
0          2        9  0.0    2.74  97.26
0          2       10  0.0   20.12  79.88
0          2       11  0.0   40.53  59.47
0          2       12  0.0   43.94  56.06
0          2       13  0.0  100.00   0.00
0          2       14  0.0   78.59  21.41
0          2       15  0.0    2.45  97.55
0          2       16  0.0   10.60  89.40
0          2       17  0.0   71.74  28.26
0          2       18  0.0   89.58  10.42
0          2       19  0.0   21.61  78.39

  Simulacion Paciente  TBR     TIR    TAR
0          3        0  0.0   94.93   5.07
0          3        1  0.0   99.31   0.69
0          3        2  0.0   29.18  70.82
0          3        3  0.0   29.94  70.06
0          3        4  0.0    2.13  97.87
0          3        5  0.0  100.00   0.00
0          3        6  0.0   91.14   8.86
0          3        7  0.0   99.70   0.30
0          3        8  0.0    3.65  96.35
0          3        9  0.0    1.81  98.19
0          3       10  0.0   31.72  68.28
0          3       11  0.0   45.03  54.97
0          3       12  0.0   68.39  31.61
0          3       13  0.0  100.00   0.00
0          3       14  0.0   86.91  13.09
0          3       15  0.0    2.38  97.62
0          3       16  0.0   15.74  84.26
0          3       17  0.0   74.68  25.32
0          3       18  0.0   91.23   8.77
0          3       19  0.0   38.24  61.76

  Simulacion Paciente  TBR     TIR    TAR
0          4        0  0.0   77.56  22.44
0          4        1  0.0   97.69   2.31
0          4        2  0.0   27.85  72.15
0          4        3  0.0   18.48  81.52
0          4        4  0.0    2.25  97.75
0          4        5  0.0  100.00   0.00
0          4        6  0.0   91.60   8.40
0          4        7  0.0   99.56   0.44
0          4        8  0.0    3.47  96.53
0          4        9  0.0    3.06  96.94
0          4       10  0.0   16.92  83.08
0          4       11  0.0   38.88  61.12
0          4       12  0.0   44.14  55.86
0          4       13  0.0  100.00   0.00
0          4       14  0.0   82.25  17.75
0          4       15  0.0    2.38  97.62
0          4       16  0.0   10.84  89.16
0          4       17  0.0   70.62  29.38
0          4       18  0.0   91.10   8.90
0          4       19  0.0   25.59  74.41

  Simulacion Paciente  TBR     TIR    TAR
0          5        0  0.0   76.95  23.05
0          5        1  0.0   97.20   2.80
0          5        2  0.0   28.65  71.35
0          5        3  0.0   18.16  81.84
0          5        4  0.0    1.64  98.36
0          5        5  0.0  100.00   0.00
0          5        6  0.0   91.39   8.61
0          5        7  0.0   98.62   1.38
0          5        8  0.0    4.94  95.06
0          5        9  0.0    2.95  97.05
0          5       10  0.0   18.65  81.35
0          5       11  0.0   41.86  58.14
0          5       12  0.0   44.69  55.31
0          5       13  0.0  100.00   0.00
0          5       14  0.0   76.34  23.66
0          5       15  0.0    1.94  98.06
0          5       16  0.0   12.02  87.98
0          5       17  0.0   68.32  31.68
0          5       18  0.0   87.86  12.14
0          5       19  0.0   22.68  77.32

  Simulacion Paciente  TBR     TIR    TAR
0          6        0  0.0   90.89   9.11
0          6        1  0.0   99.08   0.92
0          6        2  0.0   29.20  70.80
0          6        3  0.0   30.28  69.72
0          6        4  0.0    2.84  97.16
0          6        5  0.0  100.00   0.00
0          6        6  0.0   90.24   9.76
0          6        7  0.0   99.01   0.99
0          6        8  0.0    6.88  93.12
0          6        9  0.0    2.66  97.34
0          6       10  0.0   30.46  69.54
0          6       11  0.0   44.38  55.62
0          6       12  0.0   68.68  31.32
0          6       13  0.0  100.00   0.00
0          6       14  0.0   87.13  12.87
0          6       15  0.0    2.47  97.53
0          6       16  0.0   16.44  83.56
0          6       17  0.0   73.81  26.19
0          6       18  0.0   90.76   9.24
0          6       19  0.0   38.23  61.77

  Simulacion Paciente  TBR     TIR    TAR
0          7        0  0.0   77.72  22.28
0          7        1  0.0   92.95   7.05
0          7        2  0.0   29.90  70.10
0          7        3  0.0   14.31  85.69
0          7        4  0.0    6.27  93.73
0          7        5  0.0  100.00   0.00
0          7        6  0.0   90.37   9.63
0          7        7  0.0   98.90   1.10
0          7        8  0.0    5.24  94.76
0          7        9  0.0    1.97  98.03
0          7       10  0.0   23.47  76.53
0          7       11  0.0   41.93  58.07
0          7       12  0.0   45.69  54.31
0          7       13  0.0  100.00   0.00
0          7       14  0.0   72.66  27.34
0          7       15  0.0    3.57  96.43
0          7       16  0.0   11.04  88.96
0          7       17  0.0   66.84  33.16
0          7       18  0.0   88.93  11.07
0          7       19  0.0   24.33  75.67

  Simulacion Paciente  TBR     TIR    TAR
0          8        0  0.0   83.32  16.68
0          8        1  0.0   97.86   2.14
0          8        2  0.0   26.77  73.23
0          8        3  0.0   17.34  82.66
0          8        4  0.0    4.49  95.51
0          8        5  0.0  100.00   0.00
0          8        6  0.0   90.65   9.35
0          8        7  0.0   97.69   2.31
0          8        8  0.0   11.15  88.85
0          8        9  0.0    2.89  97.11
0          8       10  0.0   17.48  82.52
0          8       11  0.0   43.99  56.01
0          8       12  0.0   41.82  58.18
0          8       13  0.0   99.89   0.11
0          8       14  0.0   69.06  30.94
0          8       15  0.0    3.04  96.96
0          8       16  0.0   10.31  89.69
0          8       17  0.0   69.49  30.51
0          8       18  0.0   87.91  12.09
0          8       19  0.0   22.86  77.14

  Simulacion Paciente  TBR     TIR    TAR
0          9        0  0.0   85.83  14.17
0          9        1  0.0   97.77   2.23
0          9        2  0.0   29.22  70.78
0          9        3  0.0   23.56  76.44
0          9        4  0.0    4.57  95.43
0          9        5  0.0  100.00   0.00
0          9        6  0.0   92.03   7.97
0          9        7  0.0   98.81   1.19
0          9        8  0.0    7.10  92.90
0          9        9  0.0    4.71  95.29
0          9       10  0.0   30.93  69.07
0          9       11  0.0   45.08  54.92
0          9       12  0.0   68.32  31.68
0          9       13  0.0   99.95   0.05
0          9       14  0.0   79.69  20.31
0          9       15  0.0    3.62  96.38
0          9       16  0.0   12.64  87.36
0          9       17  0.0   72.80  27.20
0          9       18  0.0   88.37  11.63
0          9       19  0.0   33.51  66.49