In [1]:
print('hello')

hello

In [2]:
import pandas as pd 
import numpy as np
import pickle

Carga de los datasets

In [10]:
datos = dict()
for i in range(1,7):
    nombre_archivo = f"../Simulaciones/sim_{i}_data.pkl"

    with open(nombre_archivo, 'rb') as f:
        datos_recuperados = pickle.load(f)
    datos[i]=datos_recuperados
    print(type(datos_recuperados),len(datos_recuperados))

<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20
<class 'dict'> 20

Remuestreo

In [11]:
from Funciones import remuestrear
datos_prueba = {'t_min': list(range(1,14)),
    'valores': [0, 10, 0, 0, 20, 0, 0, 30, 0, 0, 0, 40, 0]
}
df = pd.DataFrame(datos_prueba)

print("DataFrame Original:")
print(df)

salida = remuestrear(df, ['t_min', 'valores'], 5)
print("\nDataFrame con los valores desplazados:")
print(salida)

DataFrame Original:
    t_min  valores
0       1        0
1       2       10
2       3        0
3       4        0
4       5       20
5       6        0
6       7        0
7       8       30
8       9        0
9      10        0
10     11        0
11     12       40
12     13        0

DataFrame con los valores desplazados:
    t_min  valores
0       6       10
5      30       50
10     55       40

In [13]:
datos.keys()

dict_keys([1, 2, 3, 4, 5, 6])

In [15]:
remuestrear(datos[3]['p_0'],columnas = ['meal_carb', 'snack_carb',
                                                     'bolus_insulin', 'basal_insulin'],
                                         t_muestreo=5)

,t_min,glu_mmol,gluc_mg,meal_carb,snack_carb,bolus_insulin,basal_insulin,running_speed
0,0,6.000000,108.0,0.0,0.0,0.0,30.013287,0.0
5,5,6.000000,108.0,0.0,0.0,0.0,0.000000,0.0
10,10,6.000000,108.0,0.0,0.0,0.0,0.000000,0.0
15,15,5.999987,108.0,0.0,0.0,0.0,0.000000,0.0
20,20,5.999729,108.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...
43180,43180,9.728406,175.0,0.0,0.0,0.0,0.000000,0.0
43185,43185,9.669671,174.0,0.0,0.0,0.0,0.000000,0.0
43190,43190,9.610650,173.0,0.0,0.0,0.0,0.000000,0.0
43195,43195,9.551680,172.0,0.0,0.0,0.0,0.000000,0.0
43200,0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0

In [ ]:
for s in range(1,7):
    for p in range(20):
        print(f'p{p}')
        datos[s][f'p_{p}'] = remuestrear(datos[i][f'p_{p}'],
                                         columnas = ['meal_carb', 'snack_carb','bolus_insulin', 'basal_insulin'],
                                         t_muestreo=5)

p0
p1
p2
p3
p4
p5
p6
p7
p8
p9
p10
p11
p12
p13
p14
p15
p16
p17
p18
p19
p0
p1
p2
p3
p4
p5
p6
p7
p8
p9
p10
p11
p12
p13
p14
p15
p16
p17
p18
p19
p0
p1
p2
p3
p4
p5
p6

In [5]:
def estadisticas_rango(df, nombre_col = 'gluc_mg', lim = [0, 70, 180, 700], n_rang = ['TBR','TIR','TAR']):
    est =pd.DataFrame()
    columna = nombre_col

    # 2. Definimos los límites de los rangos (bins)
    # Esto creará los rangos: (0-70], (70-180], (180-700]
    limites = lim

    # 3. Definimos etiquetas para que el resultado sea más fácil de leer
    nombres_rangos = n_rang

    # 4. Clasificamos los valores de la columna en los rangos usando pd.cut()
    est['Tiempo_en_rango'] = pd.cut(df[columna], bins=limites, labels=nombres_rangos)

    # 5. Calculamos el porcentaje
    porcentajes = est['Tiempo_en_rango'].value_counts(normalize=True) * 100

    porcentajes_ok = {'TIR':[round(porcentajes['TIR'],2)],
                      'TAR':[round(porcentajes['TAR'],2)],
                      'TBR':[round(porcentajes['TBR'],2)]}
    return porcentajes_ok

estadisticas_rango(datos[1]['p_2'])

{'TIR': [27.99], 'TAR': [72.01], 'TBR': [0.0]}

In [6]:
est = pd.DataFrame(columns=['Simulacion','Paciente', 'TBR', 'TIR', 'TAR'])
# display(est)
for simu in range(1,7):
    for p in range(20):
        est_l = estadisticas_rango(datos[simu][f'p_{p}'])
        est_l.update({'Simulacion': [simu], 'Paciente': [p]})
        df_l = pd.DataFrame(est_l)
        est = pd.concat([est, df_l])
# est.head(20)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18796\3298077384.py:8: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  est = pd.concat([est, df_l])

In [7]:
for i in range(1,7):
    display(est[est['Simulacion']==i])

  Simulacion Paciente  TBR     TIR    TAR
0          1        0  0.0   81.41  18.59
0          1        1  0.0   98.31   1.69
0          1        2  0.0   27.99  72.01
0          1        3  0.0   24.59  75.41
0          1        4  0.0    1.64  98.36
0          1        5  0.0  100.00   0.00
0          1        6  0.0   91.11   8.89
0          1        7  0.0   99.83   0.17
0          1        8  0.0    3.43  96.57
0          1        9  0.0    1.92  98.08
0          1       10  0.0   23.01  76.99
0          1       11  0.0   38.75  61.25
0          1       12  0.0   40.13  59.87
0          1       13  0.0  100.00   0.00
0          1       14  0.0   83.96  16.04
0          1       15  0.0    1.75  98.25
0          1       16  0.0   10.03  89.97
0          1       17  0.0   73.28  26.72
0          1       18  0.0   91.28   8.72
0          1       19  0.0   20.95  79.05

  Simulacion Paciente  TBR     TIR    TAR
0          2        0  0.0   80.74  19.26
0          2        1  0.0   98.09   1.91
0          2        2  0.0   28.67  71.33
0          2        3  0.0   20.40  79.60
0          2        4  0.0    1.99  98.01
0          2        5  0.0  100.00   0.00
0          2        6  0.0   91.54   8.46
0          2        7  0.0   98.67   1.33
0          2        8  0.0    3.82  96.18
0          2        9  0.0    2.74  97.26
0          2       10  0.0   20.12  79.88
0          2       11  0.0   40.53  59.47
0          2       12  0.0   43.94  56.06
0          2       13  0.0  100.00   0.00
0          2       14  0.0   78.59  21.41
0          2       15  0.0    2.45  97.55
0          2       16  0.0   10.60  89.40
0          2       17  0.0   71.74  28.26
0          2       18  0.0   89.58  10.42
0          2       19  0.0   21.61  78.39

  Simulacion Paciente  TBR     TIR    TAR
0          3        0  0.0   94.93   5.07
0          3        1  0.0   99.31   0.69
0          3        2  0.0   29.18  70.82
0          3        3  0.0   29.94  70.06
0          3        4  0.0    2.13  97.87
0          3        5  0.0  100.00   0.00
0          3        6  0.0   91.14   8.86
0          3        7  0.0   99.70   0.30
0          3        8  0.0    3.65  96.35
0          3        9  0.0    1.81  98.19
0          3       10  0.0   31.72  68.28
0          3       11  0.0   45.03  54.97
0          3       12  0.0   68.39  31.61
0          3       13  0.0  100.00   0.00
0          3       14  0.0   86.91  13.09
0          3       15  0.0    2.38  97.62
0          3       16  0.0   15.74  84.26
0          3       17  0.0   74.68  25.32
0          3       18  0.0   91.23   8.77
0          3       19  0.0   38.24  61.76

  Simulacion Paciente  TBR     TIR    TAR
0          4        0  0.0   77.72  22.28
0          4        1  0.0   92.95   7.05
0          4        2  0.0   29.90  70.10
0          4        3  0.0   14.31  85.69
0          4        4  0.0    6.27  93.73
0          4        5  0.0  100.00   0.00
0          4        6  0.0   90.37   9.63
0          4        7  0.0   98.90   1.10
0          4        8  0.0    5.24  94.76
0          4        9  0.0    1.97  98.03
0          4       10  0.0   23.47  76.53
0          4       11  0.0   41.93  58.07
0          4       12  0.0   45.69  54.31
0          4       13  0.0  100.00   0.00
0          4       14  0.0   72.66  27.34
0          4       15  0.0    3.57  96.43
0          4       16  0.0   11.04  88.96
0          4       17  0.0   66.84  33.16
0          4       18  0.0   88.93  11.07
0          4       19  0.0   24.33  75.67

  Simulacion Paciente  TBR     TIR    TAR
0          5        0  0.0   83.32  16.68
0          5        1  0.0   97.86   2.14
0          5        2  0.0   26.77  73.23
0          5        3  0.0   17.34  82.66
0          5        4  0.0    4.49  95.51
0          5        5  0.0  100.00   0.00
0          5        6  0.0   90.65   9.35
0          5        7  0.0   97.69   2.31
0          5        8  0.0   11.15  88.85
0          5        9  0.0    2.89  97.11
0          5       10  0.0   17.48  82.52
0          5       11  0.0   43.99  56.01
0          5       12  0.0   41.82  58.18
0          5       13  0.0   99.89   0.11
0          5       14  0.0   69.06  30.94
0          5       15  0.0    3.04  96.96
0          5       16  0.0   10.31  89.69
0          5       17  0.0   69.49  30.51
0          5       18  0.0   87.91  12.09
0          5       19  0.0   22.86  77.14

  Simulacion Paciente  TBR     TIR    TAR
0          6        0  0.0   85.83  14.17
0          6        1  0.0   97.77   2.23
0          6        2  0.0   29.22  70.78
0          6        3  0.0   23.56  76.44
0          6        4  0.0    4.57  95.43
0          6        5  0.0  100.00   0.00
0          6        6  0.0   92.03   7.97
0          6        7  0.0   98.81   1.19
0          6        8  0.0    7.10  92.90
0          6        9  0.0    4.71  95.29
0          6       10  0.0   30.93  69.07
0          6       11  0.0   45.08  54.92
0          6       12  0.0   68.32  31.68
0          6       13  0.0   99.95   0.05
0          6       14  0.0   79.69  20.31
0          6       15  0.0    3.62  96.38
0          6       16  0.0   12.64  87.36
0          6       17  0.0   72.80  27.20
0          6       18  0.0   88.37  11.63
0          6       19  0.0   33.51  66.49